/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package edu.com.Panel;

import edu.com.Dialog.ThemGia;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import koalaproject.AddRowOfTable;

/**
 *
 * @author Pham The Quyen
 */
public class CacLoaiPhi extends javax.swing.JPanel {

    /**
     * Creates new form CacLoaiPhi
     */
    private DefaultTableModel model;
    public CacLoaiPhi() {
        initComponents();
     model=new DataBase.DataTable().BangDanhSachPhi(jTable3);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_CacLoaiPhi = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        Button_CacLoaiPhi_Them = new javax.swing.JLabel();
        Button_CacLoaiPhi_Sua = new javax.swing.JLabel();
        Button_CacLoaiPhi_Xoa = new javax.swing.JLabel();

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Tên", "Kì học", "Năm học", "Giá"
            }
        ));
        jScrollPane5.setViewportView(jTable3);

        Button_CacLoaiPhi_Them.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/com/image/them.jpg"))); // NOI18N
        Button_CacLoaiPhi_Them.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_CacLoaiPhi_ThemMouseClicked(evt);
            }
        });

        Button_CacLoaiPhi_Sua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/com/image/sua.JPG"))); // NOI18N
        Button_CacLoaiPhi_Sua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_CacLoaiPhi_SuaMouseClicked(evt);
            }
        });

        Button_CacLoaiPhi_Xoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/com/image/xoa.jpg"))); // NOI18N

        javax.swing.GroupLayout Panel_CacLoaiPhiLayout = new javax.swing.GroupLayout(Panel_CacLoaiPhi);
        Panel_CacLoaiPhi.setLayout(Panel_CacLoaiPhiLayout);
        Panel_CacLoaiPhiLayout.setHorizontalGroup(
            Panel_CacLoaiPhiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_CacLoaiPhiLayout.createSequentialGroup()
                .addGroup(Panel_CacLoaiPhiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_CacLoaiPhiLayout.createSequentialGroup()
                        .addComponent(Button_CacLoaiPhi_Them)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Button_CacLoaiPhi_Sua)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Button_CacLoaiPhi_Xoa))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 1100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Panel_CacLoaiPhiLayout.setVerticalGroup(
            Panel_CacLoaiPhiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_CacLoaiPhiLayout.createSequentialGroup()
                .addGroup(Panel_CacLoaiPhiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Button_CacLoaiPhi_Them)
                    .addGroup(Panel_CacLoaiPhiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(Button_CacLoaiPhi_Xoa)
                        .addComponent(Button_CacLoaiPhi_Sua)))
                .addGap(7, 7, 7)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_CacLoaiPhi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Panel_CacLoaiPhi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Button_CacLoaiPhi_ThemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_CacLoaiPhi_ThemMouseClicked
        // TODO add your handling code here:
        ThemGia themgia = new ThemGia(null, true);
        themgia.setLocation(420, 130);
        themgia.show();
        if(themgia.getButton())
        {
         Vector v= new Vector();
         v.add(themgia.getTenPhi());
         v.add(themgia.getHocKy());
         v.add("2013-01-01");
         v.add(themgia.getGia());
         
         AddRowOfTable a= new AddRowOfTable();
         a.addRowOfTable(model, v);
         
        }
    }//GEN-LAST:event_Button_CacLoaiPhi_ThemMouseClicked

    private void Button_CacLoaiPhi_SuaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_CacLoaiPhi_SuaMouseClicked
        // TODO add your handling code here:
        ThemGia suagia=new ThemGia(null,true);
        suagia.setLocation(420, 130);
        suagia.show();
    }//GEN-LAST:event_Button_CacLoaiPhi_SuaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Button_CacLoaiPhi_Sua;
    private javax.swing.JLabel Button_CacLoaiPhi_Them;
    private javax.swing.JLabel Button_CacLoaiPhi_Xoa;
    private javax.swing.JPanel Panel_CacLoaiPhi;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable3;
    // End of variables declaration//GEN-END:variables
}
